version: '3'

services:
  node:
    image: mysql:8.0-debian
    container_name: mysql-go-blogs
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=drftgy
      - MYSQL_DATABASE= default_schema
      - MYSQL_USER= test
      - MYSQL_PASSWORD= test
      - MYSQL_TCP_PORT= 3307
    ports:
      - "3307:3307"
